spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://localhost:3306/ayondb
    username: ayon
    password: ayon123pass
    initialize: false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: false
      maximum-pool-size: 5


  jpa:
    show-sql: true # Show or not log for each sql query
    hibernate:
      # Hibernate ddl auto (create, create-drop, update): with "update" the database
      # schema will be automatically updated accordingly to java entities found in
      # the project
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true



# the port where my program will be serving
# these are system variable better not change these
server:
  port: 3194
